version: "3.7"

services:
  nginx:
    build:
      context: ./config/docker/nginx
      dockerfile: ./Dockerfile
    depends_on:
      - "php"
    init: true
    ports:
      - "8000:80"
    volumes:
      - ./web:/app/web:cached
  php:
    build:
      context: ./config/docker/php
      dockerfile: ./Dockerfile
    expose:
      - "9000"
    init: true
    volumes:
      # - storage:/app/storage:delegated
      - .:/app:cached
      # - ./vendor:/app/vendor:delegated
  node:
    build:
      context: ./config/docker/node
      dockerfile: ./Dockerfile
    command: [sh, -c, "npm install && npm run dev"]
    init: true
    ports:
      - "8080:8080"
    volumes:
      - .:/app:cached
      # - ./node_modules:/app/node_modules:delegated
      # - ./web/dist:/app/web/dist:delegated

volumes:
  storage:
